# Generated by Django 5.1.6 on 2025-03-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
            },
        ),
        migrations.RemoveField(
            model_name="account",
            name="code",
        ),
        migrations.RemoveField(
            model_name="account",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="account",
            name="type",
        ),
        migrations.RemoveField(
            model_name="account",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="شماره حساب/کارت"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("cash", "نقدی"),
                    ("bank", "حساب بانکی"),
                    ("card", "کارت بانکی"),
                    ("digital", "کیف پول دیجیتال"),
                ],
                default="cash",
                max_length=20,
                verbose_name="نوع حساب",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bank_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="نام بانک"),
        ),
        migrations.AddField(
            model_name="account",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="موجودی اولیه"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="core.account",
                verbose_name="حساب",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_transactions",
                to="core.account",
                verbose_name="حساب مقصد/مبدا",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="related_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.transaction",
                verbose_name="تراکنش مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "درآمد"),
                    ("expense", "هزینه"),
                    ("transfer_in", "دریافت انتقالی"),
                    ("transfer_out", "پرداخت انتقالی"),
                ],
                default="expense",
                max_length=20,
                verbose_name="نوع تراکنش",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.DeleteModel(
            name="Budget",
        ),
    ]
