# Generated by Django 5.1.6 on 2025-03-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_transaction_options_remove_account_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="related_transaction",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="core.account",
                verbose_name="حساب",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="related_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="related_transactions",
                to="core.account",
                verbose_name="حساب مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "درآمد"),
                    ("expense", "هزینه"),
                    ("transfer", "انتقال"),
                ],
                default="expense",
                max_length=20,
                verbose_name="نوع تراکنش",
            ),
        ),
    ]
