# Generated by Django 5.1.6 on 2025-03-05 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportchart",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "نمودار گزارش",
                "verbose_name_plural": "نمودارهای گزارش",
            },
        ),
        migrations.AddField(
            model_name="financialreport",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="reportchart",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="reportchart",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
        migrations.AddField(
            model_name="reportchart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AddField(
            model_name="reportperiod",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="reportperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="reportchart",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charts",
                to="reports.financialreport",
                verbose_name="گزارش مالی",
            ),
        ),
    ]
